# 代码高亮，需要安装rdiscount
markdown: rdiscount
highlighter: pygments
excerpt_separator: "<!--more-->"

# 文章结构 /分类/标题
permalink:   /:categories/:title/
url: http://lindabigwheel.github.io/blog
# 部署在Git上的repo名字
baseurl: /blog
# 名字
author: Linda
# 邮箱
gmail: 'gaoxing.gx@alibaba-inc.com'
# 个人logo文件路径
logo: /assets/images/logo.jpg
# 站点开始时间
date: 2015-03-10

# 个人信息，用于footer
# contain:github, gmail, twitter, sina; lack:gplus
contacts:
  - type: github
    icon: fa-github
    url: 'https://github.com/lindabigwheel'
  - type: gmail
    icon: fa-pencil
    url: 'mailto:gaoxing.gx@alibaba-inc.com'
  - type: sina
    icon: fa-weibo
    url: 'http://weibo.com/7gaoxing'

# 链接，用于导航菜单
# 包含 about（关于）/articles（文章归档）/tags（标签分类）/feed（feed源）/search（搜索功能）
links:
  - title: About
    url: /about
    icon: fa-anchor
    link: normal
  - title: Articles
    url: /
    icon: fa-bookmark
    link: normal
  - title: tags
    url: /tags
    icon: fa-tags
    link: normal
  - title: Feed
    url: /feed.xml
    icon: fa-rss-square
    normalLink: false
    link: feed
  - title: Search
    icon: fa-search
    normalLink: false
    link: search

safe: false
# Blog标题
title: BigWheel
# Blog描述
description: Who is Linda, When to see Big Wheel

# 开启搜索功能
search: true

# 开启图片预览功能，未实现，设置为false
imgPreview: false

# 多说评论
comments: false

# 时间显示
showTime: true

